#!/usr/bin/env bash
# Phase: provision the timestamping objects through scripts/timestamping-setup.sh and
# hand the suite a machine-readable summary of what exists.
#
# The setup script reuses every named object it finds but always issues a fresh certificate
# for a set it has to create, so the certificate DN and the key name must be unique per
# *fresh* provisioning: EJBCA rejects a second end entity bound to an already-used key.
# Both names are therefore pinned in .state/provisioning.env for as long as the database
# survives, and regenerated whenever that state is gone (first run, or after --clean).

provisioning_state_file() { echo "${SUITE_DIR}/.state/provisioning.env"; }

load_or_create_provisioning_names() {
  local state_file
  state_file=$(provisioning_state_file)
  mkdir -p "$(dirname "$state_file")"

  if [[ -f "$state_file" ]]; then
    # shellcheck disable=SC1090
    source "$state_file"
    # A state file written before ML-DSA coverage existed carries only the RSA names.
    if [[ -z "${MLDSA_CERTIFICATE_DN:-}" ]]; then
      MLDSA_CERTIFICATE_DN="regression-mldsa-$(date +%Y%m%d-%H%M%S)"
      MLDSA_KEY_NAME="tsa-mldsa-${MLDSA_CERTIFICATE_DN##*-mldsa-}"
      write_provisioning_state
    fi
    log "reusing provisioning identity from $(basename "$state_file"): ${CERTIFICATE_DN}"
    return 0
  fi

  rotate_provisioning_names
  log "new provisioning identity: ${CERTIFICATE_DN}"
}

# A failed attempt may already have issued a certificate and bound the key to an EJBCA end
# entity, and EJBCA refuses a second end entity on the same key. Every attempt after a
# failure therefore starts from fresh names.
rotate_provisioning_names() {
  local stamp; stamp=$(date +%Y%m%d-%H%M%S)
  CERTIFICATE_DN="regression-${stamp}"
  KEY_NAME="tsa-rsa-${stamp}"
  MLDSA_CERTIFICATE_DN="regression-mldsa-${stamp}"
  MLDSA_KEY_NAME="tsa-mldsa-${stamp}"
}

write_provisioning_state() {
  cat > "$(provisioning_state_file)" <<EOF
# Generated by the timestamping regression runner. Delete to force fresh certificates.
CERTIFICATE_DN="${CERTIFICATE_DN}"
KEY_NAME="${KEY_NAME}"
MLDSA_CERTIFICATE_DN="${MLDSA_CERTIFICATE_DN}"
MLDSA_KEY_NAME="${MLDSA_KEY_NAME}"
EOF
}

discard_provisioning_state() {
  rm -f "$(provisioning_state_file)"
}

# The ssl-client-cert header only authenticates once the certificate is registered as an
# administrator, which a wiped database no longer has.
bootstrap_admin_if_needed() {
  if ilm_api GET /v1/connectors >/dev/null 2>&1; then return 0; fi

  log "admin certificate not recognised — registering it through the Local API"
  local cert_b64 payload response
  cert_b64=$(sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' "$ADMIN_CERT_PEM" \
    | grep -v "^-----" | tr -d '\n\r')
  payload=$(jq -n --arg cert "$cert_b64" \
    '{certificateData: $cert, certificateUuid: "", username: "adminadmin", firstname: "admin",
      lastname: "admin", email: "admin@ilm.local", enabled: "true", description: "First Administrator"}')
  response=$(curl -s -X POST -H 'content-type: application/json' -d "$payload" \
    "${ILM_HOST}/api/v1/local/admins" 2>&1) || true

  ilm_api GET /v1/connectors >/dev/null 2>&1 \
    || die "Admin certificate still not accepted after bootstrapping. Local API said: ${response}"
  ok "administrator registered"
}

run_setup_script() {
  local log_file="$1"
  # The connectors are registered by their host-published ports in both modes; only the host
  # differs, because a containerised Core reaches those ports through the host gateway.
  "${TIMESTAMPING_SETUP_SCRIPT}" \
    --ilm-host "$ILM_HOST" \
    --connector-host "$CONNECTOR_HOST" \
    --client-cert-pem "$ADMIN_CERT_PEM" \
    --pkcs12-bundle "$EJBCA_PKCS12_BUNDLE" \
    --pkcs12-password "$EJBCA_PKCS12_PASSWORD" \
    --certificate-dn "$CERTIFICATE_DN" \
    --key-name "$KEY_NAME" \
    --json-summary "${RUN_DIR}/provisioning.json" \
    > "$log_file" 2>&1
}

# The ML-DSA counterpart of the RSA sets: the same objects, issued under the post-quantum CA
# from a key the cryptography provider generates as ML-DSA. Every name base is distinct, so
# both families coexist and the suite can exercise either.
#
# The signing key algorithm is the only deliberate difference. Anything else that diverges
# between the two families is a finding, which is the point of provisioning them side by side.
run_mldsa_setup_script() {
  local log_file="$1"
  "${TIMESTAMPING_SETUP_SCRIPT}" \
    --ilm-host "$ILM_HOST" \
    --connector-host "$CONNECTOR_HOST" \
    --client-cert-pem "$ADMIN_CERT_PEM" \
    --pkcs12-bundle "$EJBCA_PKCS12_BUNDLE" \
    --pkcs12-password "$EJBCA_PKCS12_PASSWORD" \
    --certificate-dn "$MLDSA_CERTIFICATE_DN" \
    --key-name "$MLDSA_KEY_NAME" \
    --key-algorithm MLDSA \
    --ejbca-ca "$MLDSA_EJBCA_CA" \
    --ra-profile-name "${MLDSA_NAME_BASE}" \
    --tsp-profile-name "tsp-mldsa" \
    --signing-profile-name "${MLDSA_NAME_BASE}" \
    --json-summary "${RUN_DIR}/provisioning-mldsa.json" \
    > "$log_file" 2>&1
}

# The suite reads one summary. The ML-DSA sets join the RSA ones under their own set names, so
# a spec can pick a family explicitly and an environment provisioned without ML-DSA simply has
# fewer sets rather than a different shape.
merge_mldsa_provisioning_summary() {
  local mldsa="${RUN_DIR}/provisioning-mldsa.json"
  [[ -f "$mldsa" ]] || return 0
  add_sets_to_summary "${RUN_DIR}/provisioning.json" "$mldsa" && return 0
  warn "could not merge the ML-DSA provisioning summary; ML-DSA specs will skip"
  return 1
}

# add_sets_to_summary MERGED SUMMARY [LABEL] adds SUMMARY's named sets to MERGED, which starts as
# SUMMARY when absent. LABEL names the sets' family in test titles; without one, the specs use
# the key algorithm.
add_sets_to_summary() {
  local merged="$1" summary="$2" label="${3:-}" tmp="${1}.tmp" base="null"
  [[ -f "$merged" ]] && base=$(<"$merged")
  if jq --argjson base "$base" --arg label "$label" '
       (.sets | if $label == "" then . else map_values(. + {label: $label}) end) as $sets
       | ($base // .) + {sets: (($base.sets // {}) + $sets)}' "$summary" > "$tmp" \
     && mv "$tmp" "$merged"; then
    chmod 600 "$merged" 2>/dev/null || true
    return 0
  fi
  rm -f "$tmp"
  return 1
}

# The specs read the summary keyed by set name, which timestamping-setup.sh writes from
# development-environment a0c3297 on. That revision also introduced --set-name.
require_named_set_summary() {
  grep -q -- '--set-name)' "$TIMESTAMPING_SETUP_SCRIPT" \
    || die "${TIMESTAMPING_SETUP_SCRIPT} writes a provisioning summary the suite cannot read. Point TIMESTAMPING_SETUP_SCRIPT at a timestamping-setup.sh from development-environment a0c3297 or later."
}

# --- Repair: issuing CA missing from the platform -----------------------------
# Symptom: "issuerCertificateUuid is still empty after N attempts", later surfacing as
# "Certificate is not eligible for signing workflow type TIMESTAMPING". The leaf cannot be
# validated because its issuer was never uploaded, so the signing profile is refused.
# Fix: pull the CA from the leaf's AIA extension, upload it, trust it, revalidate the leaf.
needs_issuer_ca_repair() {
  grep -q -e "issuerCertificateUuid is still empty" \
          -e "not eligible for signing workflow type TIMESTAMPING" "$1"
}

newest_certificate_uuid_by_common_name() {
  local common_name="$1" response
  response=$(ilm_api POST /v1/certificates -d '{"itemsPerPage":100,"pageNumber":1,"filters":[]}') || return 1
  echo "$response" | jq -r --arg cn "$common_name" \
    '[.certificates[]? | select(.commonName == $cn)] | sort_by(.notBefore) | last | .uuid // empty'
}

upload_and_trust_issuer_ca() {
  local leaf_uuid="$1" work_dir="${RUN_DIR}/repair"
  mkdir -p "$work_dir"

  local leaf_json content aia_uri issuer_dn ca_b64 upload_response root_uuid
  leaf_json=$(ilm_api GET "/v1/certificates/${leaf_uuid}") || return 1
  content=$(echo "$leaf_json" | jq -r '.certificateContent // empty')
  [[ -n "$content" ]] || { warn "repair: leaf ${leaf_uuid} has no certificate content"; return 1; }

  printf -- "-----BEGIN CERTIFICATE-----\n%s\n-----END CERTIFICATE-----\n" "$content" > "${work_dir}/leaf.pem"
  aia_uri=$(openssl x509 -in "${work_dir}/leaf.pem" -noout -ext authorityInfoAccess 2>/dev/null \
    | sed -n 's/.*CA Issuers - URI:\(.*\)/\1/p' | head -1 | tr -d '[:space:]')

  if [[ -n "$aia_uri" ]]; then
    log "repair: fetching the issuing CA from ${aia_uri}"
    curl -s -f -o "${work_dir}/issuer.der" "$aia_uri" \
      || { warn "repair: could not download ${aia_uri}"; return 1; }
    ca_b64=$(base64 < "${work_dir}/issuer.der" | tr -d '\n')
  else
    issuer_dn=$(echo "$leaf_json" | jq -r '.issuerDn // empty')
    [[ -n "$issuer_dn" ]] \
      || { warn "repair: leaf has neither a CA Issuers URI nor a known issuer DN"; return 1; }
    fetch_ca_from_ejbca "$issuer_dn" "${work_dir}/issuer.pem" || return 1
    ca_b64=$(grep -v -- "-----" "${work_dir}/issuer.pem" | tr -d '\n\r')
  fi

  upload_response=$(ilm_api POST /v1/certificates/upload \
    -d "$(jq -n --arg cert "$ca_b64" '{certificate: $cert, customAttributes: []}')") \
    || { warn "repair: CA upload failed: ${upload_response}"; return 1; }
  root_uuid=$(echo "$upload_response" | jq -r '.uuid // empty')
  [[ -n "$root_uuid" ]] || { warn "repair: upload returned no UUID: ${upload_response}"; return 1; }

  ilm_api PATCH "/v1/certificates/${root_uuid}" -d '{"trustedCa": true}' >/dev/null \
    || { warn "repair: could not mark ${root_uuid} as trusted"; return 1; }
  # Trusting the root does not revalidate anything by itself; ask for the leaf's validation.
  ilm_api GET "/v1/certificates/${leaf_uuid}/validate" >/dev/null || true
  ok "repair: issuing CA ${root_uuid} uploaded and trusted"
}

# The issuer of an ML-DSA leaf is reachable only by name: EJBCA's certificate distribution
# servlet serves a CA certificate by its subject DN, which is exactly what the leaf reports
# as its issuer.
fetch_ca_from_ejbca() {
  local issuer_dn="$1" destination="$2" url
  url="${EJBCA_PUBLIC_WEB_BASE}/publicweb/webdist/certdist?cmd=cacert&issuer=$(url_encode "$issuer_dn")&level=0"

  log "repair: leaf carries no CA Issuers URI; fetching '${issuer_dn}' from EJBCA"
  curl -s -f -o "$destination" "$url" \
    || { warn "repair: could not download the CA for '${issuer_dn}' from ${EJBCA_PUBLIC_WEB_BASE}"; return 1; }
  # A misnamed CA yields an HTML error page with HTTP 200, so confirm it really is a certificate.
  openssl x509 -in "$destination" -noout -subject >/dev/null 2>&1 \
    || { warn "repair: ${url} did not return a certificate"; return 1; }
}

url_encode() {
  jq -rn --arg value "$1" '$value | @uri'
}

attempt_issuer_ca_repair() {
  local prefix="${1:-$CERTIFICATE_DN}" leaf_uuid suffix
  for suffix in non-qualified qualified; do
    leaf_uuid=$(newest_certificate_uuid_by_common_name "${prefix}-${suffix}") || continue
    [[ -n "$leaf_uuid" ]] || continue
    upload_and_trust_issuer_ca "$leaf_uuid" && return 0
  done
  return 1
}

phase_provision() {
  section "Provisioning"
  require_named_set_summary
  load_or_create_provisioning_names
  bootstrap_admin_if_needed

  # The identity is only recorded once a run has actually succeeded with it; a failed
  # attempt must never be reused, because its key may already be bound in EJBCA.
  local log_file="${RUN_DIR}/provisioning.log"
  if run_setup_script "$log_file"; then
    write_provisioning_state
    ok "provisioning complete — summary: ${RUN_DIR}/provisioning.json"
    provision_mldsa_sets
    return 0
  fi

  discard_provisioning_state

  if ! needs_issuer_ca_repair "$log_file"; then
    tail -25 "$log_file" >&2
    die "Provisioning failed — full log: ${log_file}"
  fi

  warn "provisioning failed because the issuing CA is not in the platform; repairing and retrying once"
  attempt_issuer_ca_repair || { tail -25 "$log_file" >&2; die "Repair failed — full log: ${log_file}"; }

  rotate_provisioning_names
  log "retrying with ${CERTIFICATE_DN}"

  log_file="${RUN_DIR}/provisioning-retry.log"
  run_setup_script "$log_file" || { tail -25 "$log_file" >&2; die "Provisioning failed after repair — full log: ${log_file}"; }
  write_provisioning_state
  ok "provisioning complete after repair — summary: ${RUN_DIR}/provisioning.json"
  provision_mldsa_sets
}

# ML-DSA is additional coverage, not the subject of the suite: a platform that cannot
# provision it still has to pass everything else. A failure here is therefore reported and
# the run continues without the ML-DSA sets, which the specs skip on their own.
provision_mldsa_sets() {
  [[ "$MLDSA_ENABLED" == "true" ]] || { log "ML-DSA sets disabled (MLDSA_ENABLED=${MLDSA_ENABLED})"; return 0; }

  local log_file="${RUN_DIR}/provisioning-mldsa.log"
  log "provisioning the ML-DSA sets (ML-DSA-65, CA '${MLDSA_EJBCA_CA}')"
  if run_mldsa_setup_script "$log_file"; then
    merge_mldsa_provisioning_summary
    ok "ML-DSA provisioning complete"
    return 0
  fi

  if ! needs_issuer_ca_repair "$log_file"; then
    warn "ML-DSA provisioning failed — continuing without it; full log: ${log_file}"
    tail -10 "$log_file" >&2
    return 0
  fi

  warn "ML-DSA provisioning failed because the post-quantum CA is not in the platform; repairing and retrying once"
  if ! attempt_issuer_ca_repair "$MLDSA_CERTIFICATE_DN"; then
    warn "ML-DSA CA repair failed — continuing without the ML-DSA sets; full log: ${log_file}"
    return 0
  fi

  # The first attempt already bound this DN to an EJBCA end entity, and EJBCA refuses a
  # second one on the same name, so the retry needs fresh names of its own.
  local stamp; stamp=$(date +%Y%m%d-%H%M%S)
  MLDSA_CERTIFICATE_DN="regression-mldsa-${stamp}"
  MLDSA_KEY_NAME="tsa-mldsa-${stamp}"
  log "retrying the ML-DSA sets with ${MLDSA_CERTIFICATE_DN}"

  log_file="${RUN_DIR}/provisioning-mldsa-retry.log"
  if run_mldsa_setup_script "$log_file"; then
    merge_mldsa_provisioning_summary
    write_provisioning_state
    ok "ML-DSA provisioning complete after repair"
  else
    warn "ML-DSA provisioning failed after repair — continuing without it; full log: ${log_file}"
    tail -10 "$log_file" >&2
  fi
}
